# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 059ef3763fa28dc6dfe99b98ebbffd04d66c52d3cdd1d4fb1ecd41a2e531131e03ace24a854685f0a04247310b8c10990f393f12fcbd94017cb74cc98ffbf920

test:
  secret_key_base: ca3aef518bcb265504408bdfc38c262a5c09d12d267489d47bc1afcca091f3c380241c0b1b2f380d3e9eb2ee4b80bee8edd3949e73312417a9f450e4f0ccaffa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
